### ISSUE TITLE
How to get data in ./data/split and ./data/inference ?

### ISSUE THREAD

**Issue by lydia07** [zhaozj89/Educational-Question-Generation#1]
Hi, I try to run your code, but I don't know how to get the data in ./data/split and ./data/inference. Could you please explain it more clearly?

**Comment by lydia07** [comment]
> Hi, I try to run your code, but I don't know how to get the data in ./data/split and ./data/inference. Could you please explain it more clearly?

How can I get the transformed QA statements?

**Comment by zhaozj89** [comment]
Hi, thanks for your interest and sorry for the confusion. `./data/split` should have the original FairytaleQA dataset, which you can find it [here](https://github.com/uci-soe/FairytaleQAData). For the QA statements that you should put in `./data/inference`, I used the implementation in `https://github.com/kelvinguu/qanli` to get the transformation. You may need to modify some parts in `qanli` to run it. Because I do not own FairytaleQA, I do not put my transformed QA statements in the repository. If you want to get a copy of mine, please write me an email with your name, purpose of use, affiliation, etc. to zzhaoao@nuist.edu.cn. Thanks very much for your understanding.

**Comment by lydia07** [comment]
> Hi, thanks for your interest and sorry for the confusion. `./data/split` should have the original FairytaleQA dataset, which you can find it [here](https://github.com/uci-soe/FairytaleQAData). For the QA statements that you should put in `./data/inference`, I used the implementation in `https://github.com/kelvinguu/qanli` to get the transformation. You may need to modify some parts in `qanli` to run it. Because I do not own FairytaleQA, I do not put my transformed QA statements in the repository. If you want to get a copy of mine, please write me an email with your name, purpose of use, affiliation, etc. to [zzhaoao@nuist.edu.cn](mailto:zzhaoao@nuist.edu.cn). Thanks very much for your understanding.

Thank you so much. It helps me a lot!
